### ISSUE TITLE
Do not highlight the update only if the difference in the minor version

### ISSUE THREAD

**Issue by XVilka** [mhinz/vim-crates#1]
For example if you have something like
```yaml
serde_json = "1.0"
```
and you invoke `CratesToggle` it will show pink `1.0.41` as an update available. But if the lowest version is not specified cargo will take the highest possible variant of 1.0.x anyway. Maybe it's not necessary to indicate that if the difference only is in the last number? And show the update if `1.1.y` was released (or higher) only?

**Comment by mhinz** [comment]
Sure, can do that.

Just one design question.. for comparing semver numbers, `1.0` gets normalized to `1.0.0` in the process. So, assuming there would be a newer version `1.1.0`, it would show exactly that. But should it just show `1.1` instead, keeping the shorter format the maintainer chose?

**Comment by XVilka** [comment]
I think showing the full version is perfectly fine. It's just comparison that matters here.

**Comment by mhinz** [comment]
I forgot to mention that `:CratesToggle` and `:CratesUp` use the same code to get the latest version. So would you also expect `:CratesUp` to change a line from `1.0` to `1.1.0`?

**Comment by XVilka** [comment]
Well, I think it is fine. Despite my lazyness, I prefer to do the version bumps individually, considering the implications.
