### ISSUE TITLE
Fails to perform `CratesToggle` on the particular file

### ISSUE THREAD

**Issue by XVilka** [mhinz/vim-crates#2]
See the https://github.com/radareorg/radeco/blob/master/radeco/Cargo.toml
If you run `:CratesToggle` it will show nothing, but the updates are surely available, e.g. for **base64** which is 0.10.1 in the file, but 0.11.0 is available on crates.io: https://crates.io/crates/base64

**Comment by mhinz** [comment]
Ah, it fails because the very first dep is `*` and the plugin doesn't know how to handle [wildcards](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#wildcard-requirements) yet.

Will fix this later today.

**Comment by mhinz** [comment]
Ok, I added support wildcard requirements and also improved caret requirements. Actually, it didn't realize that caret requirements were the default, so now the latest version for `1.2.3` will only be shown, if it's at least `2.0.0` etc.
