### ISSUE TITLE
Fail to understand "0.9" to "0.10" as a version upgrade

### ISSUE THREAD

**Issue by XVilka** [mhinz/vim-crates#3]
I had this in my Cargo.toml:
```yaml
pangocairo-sys = "0.9"
```
But if I check for the updates with `CratesToggle` it shows nothing, but there is an update (0.10) available: https://crates.io/crates/pangocairo-sys

**Comment by mhinz** [comment]
Don't look at the patch. It's embarassing. So far this plugin just worked by accident. 😭
