### ISSUE TITLE
More targets than List items error

### ISSUE THREAD

**Issue by XVilka** [mhinz/vim-crates#4]
When running `:CratesToggle` on https://github.com/radareorg/radeco/blob/master/radeco/Cargo.toml I see this error:
![image](https://user-images.githubusercontent.com/203261/68472093-b37f5480-025a-11ea-8462-202944b66d00.png)

**Comment by mhinz** [comment]
That's a good `Cargo.toml` for testing this plugin.. BTW, now you can use `:verb CratesToggle` to see which lines failed parsing.
